[[language]]
name = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = {command = "rust-analyzer"}
indent = {tab-width = 2, unit = "  "}
